# travis-ci integration for KiBOM

dist: xenial

language: python

python:
  - 3.6

install:
  - pip3 install -r test/requirements.txt

addons:
  apt:
    update: true

before_install:
  - apt-get install python3-pip python3-coverage python3-xlsxwriter

script:
  # Check Python code for style-guide 
  - flake8 .
    # Test that the export script works with both Python2 and Python3
  - python2 KiBOM_CLI.py test/kibom-test.xml test/out3.csv
  - python3 KiBOM_CLI.py test/kibom-test.xml test/out3.csv
  # Run the coverage tests 
  - bash ./run-tests.sh

after_success:
  - coveralls