# travis-ci integration for KiBOM

language:
  - python

python:
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install python3-pip
  - cd test && pip3 install -U -r requirements.txt && cd ..

script:
  # Check Python code for style-guide 
  - flake8 .
    # Test that the export script works with both Python2 and Python3
  - python2 KiBOM_CLI.py test/kibom-test.xml test/out3.csv
  - python3 KiBOM_CLI.py test/kibom-test.xml test/out3.csv
  # Run the coverage tests 
  - sudo bash ./run-tests.sh

after_success:
  - coveralls