# travis-ci integration for KiBOM

language:
  - python

python:
  - "2.7"
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install python3-pip
  - pip3 install -U -r test/requirements.txt

script:
  - flake8 .
